export ZSH="${HOME}/.oh-my-zsh"
export ZSH_DISABLE_COMPFIX=true
export DISABLE_AUTO_UPDATE=true
export DISABLE_UPDATE_PROMPT=true
export ENABLE_CORRECTION=false
export HISTFILE="${HOME}/.zsh_history"
export HISTSIZE=10000
export SAVEHIST=10000
export LANG="${LANG:-C.UTF-8}"
export TERM="${TERM:-xterm-256color}"

plugins=(
  git
  gh
  npm
  node
  python
  pip
)

source "${ZSH}/oh-my-zsh.sh"

autoload -Uz compinit && compinit

if [[ -f /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]]; then
  source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

if [[ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
  source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

setopt AUTO_CD
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt SHARE_HISTORY
setopt EXTENDED_GLOB

zstyle ':omz:update' mode disabled

PROMPT='%F{magenta}butler@%F{cyan}%m%f:%F{green}%~%f %# '
RPROMPT=''

alias ll='ls -lah'
alias la='ls -A'
alias l='ls -CF'
